### ISSUE TITLE
per-day stats in reading activity graph incorrect if more than one language read

### ISSUE THREAD

**Issue by pm215** [tadoku/web#526]
The per-user 'reading activity' graph shows stats for a day if you hover over a bar. However the numbers are wrong if more than one language is being read. For instance on the 2nd May I (user 'pm215') read 8 pages of French and 30 of Japanese, but the hover-over info says 8 of French and 38 of Japanese -- it seems to use the total figure for the 2nd language.

**Comment by antonve** [comment]
Thanks for reporting the bug, I'll take a look into it.

**Comment by antonve** [comment]
The fix should be live now.
