### ISSUE TITLE
Viewing Tadoku on mobile hides the footer

### ISSUE THREAD

**Issue by sheodox** [tadoku/web#699]
Below a 768px width screen the footer gets `display: none;` (more accurately the media query that gives it `display: block;` ceases to apply). Below ~500px things start to overlap so the layout would need to adjust a bit as well.

Without the footer, links to Discord, old contests, and the landing page aren't accessible.

**Comment by antonve** [comment]
It's been hidden on mobile since I never got around to designing it for mobile. I'll add this to the backlog.

**Comment by antonve** [comment]
Deployed, thanks!
