### ISSUE TITLE
Add archive of old contests

### ISSUE THREAD

**Issue by sheodox** [tadoku/web#701]
Currently the only way to find links to previous contests is to use the links in the footer, but only the most recent five contests show up (one of them being the current contest, so only four past contest links that you couldn't otherwise get to). Other than that you have to manually enter a URL to get to another old contest if you want to view an earlier one.

If it's desired that you should be able to view all contests just having an exhaustive list of links is going to get out of hand in the footer pretty quickly. Instead maybe it'd be nice to have a dedicated page for "old contests" that could include all contests at once (maybe paginated), with extra details like when the contest occurred, number of participants and top three readers? Could go lots of places with this! Just my two cents.

![image](https://user-images.githubusercontent.com/3468630/97124145-ed13ce80-16fc-11eb-915a-0ee5ad712181.png)

**Comment by antonve** [comment]
Done. Now available at https://tadoku.app/contests
